<?php
global $searchPageFilter;
$searchPageFilter = array('=ID' => array());

foreach ($arIblock['ITEMS'] as $arItem) {
    $searchPageFilter['=ID'][] = $arItem['ITEM_ID'];
}


$APPLICATION->IncludeComponent(
    "bitrix:catalog.section",
    "master",
    array(
        "ACTION_VARIABLE" => "action",
        "ADD_CONTAINER" => "N",
        "ADD_PICT_PROP" => "-",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "ADD_SECTIONS_CHAIN" => "N",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "BACKGROUND_IMAGE" => "-",
        "BLOCK_NAME_IS_LINK" => "N",
        "BROWSER_TITLE" => "-",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "COMPATIBLE_MODE" => "Y",
        "COMPONENT_TEMPLATE" => "master",
        "CURRENCY_PROP" => $arParams['CATALOG_CURRENCY_PROP'],
        "DETAIL_URL" => "",
        "DISABLE_INIT_JS_IN_COMPONENT" => "Y",
        "DISCOUNT_PROP" => $arParams['CATALOG_DISCOUNT_PROP'],
        "DISPLAY_BOTTOM_PAGER" => "N",
        "DISPLAY_COMPARE" => "N",
        "DISPLAY_TOP_PAGER" => "N",
        "ELEMENT_SORT_FIELD" => "id",
        "ELEMENT_SORT_FIELD2" => "sort",
        "ELEMENT_SORT_ORDER" => "asc",
        "ELEMENT_SORT_ORDER2" => "desc",
        "ENLARGE_PRODUCT" => "STRICT",
        "FILTER_NAME" => "searchPageFilter",
        "IBLOCK_ID" => $arParams['CATALOG_IBLOCK_ID'],
        "IBLOCK_TYPE" => $arParams['CATALOG_IBLOCK_TYPE'],
        "INCLUDE_SUBSECTIONS" => "Y",
        "IS_USE_CART" => $arParams['CATALOG_IS_USE_CART'],
        "LABEL_PROP_POSITION" => "bottom-left",
        "LAZY_LOAD" => "N",
        "LINE_ELEMENT_COUNT" => "3",
        "LOAD_ON_SCROLL" => "N",
        "MESSAGE_404" => "",
        "MESS_BTN_ADD_TO_BASKET" => $arParams['CATALOG_MESS_BTN_ADD_TO_BASKET'],
        "MESS_BTN_BUY" => $arParams['CATALOG_MESS_BTN_BUY'],
        "MESS_BTN_DETAIL" => $arParams['CATALOG_MESS_BTN_DETAIL'],
        "MESS_BTN_SUBSCRIBE" => $arParams['CATALOG_MESS_BTN_SUBSCRIBE'],
        "MESS_NOT_AVAILABLE" => $arParams['CATALOG_MESS_NOT_AVAILABLE'],
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "OFFERS_LIMIT" => "5",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGE_ELEMENT_COUNT" => "20",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRICE_CODE" => array(
        ),
        "PRICE_DECIMALS_PROP" => "0",
        "PRICE_PROP" => $arParams['CATALOG_PRICE_PROP'],
        "PRICE_VAT_INCLUDE" => "Y",
        "PRODUCT_BLOCKS_ORDER" => "preview,price,quantity,buttons",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_PROPERTIES" => array(
        ),
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false}]",
        "PROPERTY_CODE" => array(
            0 => "PRICE",
        ),
        "PROPERTY_CODE_MOBILE" => array(
        ),
        "PROP_CURRENCY" => "CURRENCY",
        "PROP_PRICE" => "PRICE",
        "PROP_PRICE_DECIMALS" => "0",
        "RCM_TYPE" => "personal",
        "SECTION_CODE" => "",
        "SECTION_ID" => "",
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "SECTION_URL" => "",
        "SECTION_USER_FIELDS" => array(
            0 => "",
            1 => "",
        ),
        "SEF_MODE" => "N",
        "SET_BROWSER_TITLE" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "N",
        "SET_META_KEYWORDS" => "N",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "N",
        "SHOW_404" => "N",
        "SHOW_ALL_WO_SECTION" => "Y",
        "SHOW_FROM_SECTION" => "Y",
        "SHOW_OLD_PRICE" => "Y",
        "SHOW_PARENT_NAME" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "USE_ENHANCED_ECOMMERCE" => "Y",
        "USE_MAIN_ELEMENT_SECTION" => "N",
        "USE_PRICE_COUNT" => "N",
        "USE_PRODUCT_QUANTITY" => "N",
        "PRICE_DECIMALS" => "0",
        "DATA_LAYER_NAME" => "dataLayer",
    ),
    false
);
?>
