<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Видео");
?>
    <div class="videopage">
        <div class="zagolovok_fon">
            <h2 class="zagolovok_text">Видео</h2>
        </div>
        <? //Главные новости
        $arrFiltervideo = array(
            "IBLOCK_ID" => 13,
            "ACTIVE" => "Y",
            "PROPERTY_main_video_VALUE" => "1",
        );
        ?> <? $APPLICATION->IncludeComponent(
            "bitrix:news.list",
            "video_main",
            Array(
                "IBLOCK_TYPE" => "news",
                "IBLOCK_ID" => "13",
                "NEWS_COUNT" => "1",
                "SORT_BY1" => "DATE_CREATE",
                "SORT_ORDER1" => "DESC",
                "SORT_BY2" => "DATE_CREATE",
                "SORT_ORDER2" => "DESC",
                "FILTER_NAME" => "arrFiltervideo",
                "FIELD_CODE" => array(0 => "DATE_CREATE", 1 => "",),
                "PROPERTY_CODE" => array(0 => "main_video", 1 => "",),
                "CHECK_DATES" => "Y",
                "DETAIL_URL" => "",
                "AJAX_MODE" => "N",
                "AJAX_OPTION_JUMP" => "N",
                "AJAX_OPTION_STYLE" => "Y",
                "AJAX_OPTION_HISTORY" => "N",
                "CACHE_TYPE" => "A",
                "CACHE_TIME" => "360000",
                "CACHE_FILTER" => "Y",
                "CACHE_GROUPS" => "Y",
                "PREVIEW_TRUNCATE_LEN" => "",
                "ACTIVE_DATE_FORMAT" => "d.m.Y H:i",
                "SET_TITLE" => "Y",
                "SET_STATUS_404" => "N",
                "INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
                "ADD_SECTIONS_CHAIN" => "Y",
                "HIDE_LINK_WHEN_NO_DETAIL" => "N",
                "PARENT_SECTION" => "",
                "PARENT_SECTION_CODE" => "",
                "INCLUDE_SUBSECTIONS" => "Y",
                "DISPLAY_TOP_PAGER" => "N",
                "DISPLAY_BOTTOM_PAGER" => "Y",
                "PAGER_TITLE" => "Новости",
                "PAGER_SHOW_ALWAYS" => "Y",
                "PAGER_TEMPLATE" => "",
                "PAGER_DESC_NUMBERING" => "N",
                "PAGER_DESC_NUMBERING_CACHE_TIME" => "3600",
                "PAGER_SHOW_ALL" => "Y",
                "DISPLAY_DATE" => "Y",
                "DISPLAY_NAME" => "Y",
                "DISPLAY_PICTURE" => "N",
                "DISPLAY_PREVIEW_TEXT" => "Y",
                "DISPLAY_IMG_WIDTH" => "80",
                "DISPLAY_IMG_HEIGHT" => "56",
                "USE_RSS" => "Y",
                "TITLE_RSS" => "Новости информационного портала",
                "AJAX_OPTION_ADDITIONAL" => ""
            )
        ); ?>

        <? $APPLICATION->IncludeComponent(
            "bitrix:news",
            "video",
            Array(
                "DISPLAY_DATE" => "Y",
                "DISPLAY_PICTURE" => "Y",
                "DISPLAY_PREVIEW_TEXT" => "Y",
                "DISPLAY_IMG_WIDTH" => "80",
                "DISPLAY_IMG_HEIGHT" => "56",
                "DISPLAY_IMG_MEDIUM_WIDTH" => "136",
                "DISPLAY_IMG_MEDIUM_HEIGHT" => "101",
                "DISPLAY_IMG_DETAIL_WIDTH" => "298",
                "DISPLAY_IMG_DETAIL_HEIGHT" => "221",
                "USE_SHARE" => "Y",
                "SHARE_HIDE" => "N",
                "SHARE_TEMPLATE" => "",
                "SHARE_HANDLERS" => array(),
                "SHARE_SHORTEN_URL_LOGIN" => "",
                "SHARE_SHORTEN_URL_KEY" => "",
                "SEF_MODE" => "Y",
                "AJAX_MODE" => "N",
                "IBLOCK_TYPE" => "news",
                "IBLOCK_ID" => "13",
                "NEWS_COUNT" => "6",
                "USE_SEARCH" => "N",
                "USE_RSS" => "Y",
                "USE_RATING" => "N",
                "USE_CATEGORIES" => "N",
                "USE_REVIEW" => "Y",
                "USE_FILTER" => "N",
                "SORT_BY1" => "ACTIVE_FROM",
                "SORT_ORDER1" => "DESC",
                "SORT_BY2" => "SORT",
                "SORT_ORDER2" => "ASC",
                "CHECK_DATES" => "Y",
                "PREVIEW_TRUNCATE_LEN" => "",
                "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y H:i",
                "LIST_FIELD_CODE" => array("DATE_ACTIVE_FROM"),
                "LIST_PROPERTY_CODE" => array("main_video"),
                "HIDE_LINK_WHEN_NO_DETAIL" => "N",
                "DISPLAY_NAME" => "Y",
                "META_KEYWORDS" => "-",
                "META_DESCRIPTION" => "-",
                "BROWSER_TITLE" => "-",
                "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y H:i",
                "DETAIL_FIELD_CODE" => array(),
                "DETAIL_PROPERTY_CODE" => array(),
                "DETAIL_DISPLAY_TOP_PAGER" => "N",
                "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
                "DETAIL_PAGER_TITLE" => "Страница",
                "DETAIL_PAGER_TEMPLATE" => "",
                "DETAIL_PAGER_SHOW_ALL" => "Y",
                "SET_TITLE" => "Y",
                "SET_STATUS_404" => "N",
                "INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
                "ADD_SECTIONS_CHAIN" => "Y",
                "USE_PERMISSIONS" => "N",
                "CACHE_TYPE" => "A",
                "CACHE_TIME" => "360000",
                "CACHE_FILTER" => "Y",
                "CACHE_GROUPS" => "Y",
                "DISPLAY_TOP_PAGER" => "N",
                "DISPLAY_BOTTOM_PAGER" => "Y",
                "PAGER_TITLE" => "Новости",
                "PAGER_SHOW_ALWAYS" => "Y",
                "PAGER_TEMPLATE" => "my",
                "PAGER_DESC_NUMBERING" => "N",
                "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                "PAGER_SHOW_ALL" => "Y",
                "NUM_NEWS" => "20",
                "NUM_DAYS" => "30",
                "YANDEX" => "N",
                "MESSAGES_PER_PAGE" => "10",
                "USE_CAPTCHA" => "Y",
                "REVIEW_AJAX_POST" => "Y",
                "PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
                "FORUM_ID" => "4",
                "URL_TEMPLATES_READ" => "",
                "SHOW_LINK_TO_FORUM" => "Y",
                "POST_FIRST_MESSAGE" => "N",
                "SEF_FOLDER" => "/video/",
                "SEF_URL_TEMPLATES" => Array(
                    "detail" => "#ELEMENT_CODE#/",
                    "rss" => "rss/",
                    "rss_section" => "#SECTION_ID#/rss/"
                ),
                "AJAX_OPTION_JUMP" => "N",
                "AJAX_OPTION_STYLE" => "Y",
                "AJAX_OPTION_HISTORY" => "N",
                "VARIABLE_ALIASES" => Array(
                    "detail" => Array(),
                    "rss" => Array(),
                    "rss_section" => Array(),
                )
            )
        ); ?>
    </div>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>